name: Docker Image CI

on:
  push:
    branches: [ "master", "*" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: docker/metadata-action@v4
      name: Docker meta
      id: meta
      with:
        images: alexazhou/toolbox
    - uses: docker/login-action@v2
      name: Login to DockerHub
      if: github.event_name != 'pull_request'
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - uses: docker/build-push-action@v3
      name: Build and push
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
